# **Importing Numpy**

In [3]:
import numpy as np

In [2]:
np

<module 'numpy' from '/home/sparsh-raj/anaconda3/envs/ml-zoomcamp/lib/python3.12/site-packages/numpy/__init__.py'>

# **Creating Arrays**

In [4]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [5]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
np.full(10,-6)

array([-6, -6, -6, -6, -6, -6, -6, -6, -6, -6])

In [8]:
a=np.array([1,2,3,5,7,12])
a

array([ 1,  2,  3,  5,  7, 12])

In [10]:
a[2]

3

In [12]:
a[2]=10
a

array([ 1,  2, 10,  5,  7, 12])

In [13]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [16]:
np.linspace(0,2,12)

array([0.        , 0.18181818, 0.36363636, 0.54545455, 0.72727273,
       0.90909091, 1.09090909, 1.27272727, 1.45454545, 1.63636364,
       1.81818182, 2.        ])

In [18]:
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [19]:
np.linspace(0,100,11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

# **MultiDimensional Arrays**

In [21]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [26]:
n=np.array([[1,2,3],
         [4,5,6],
         [7,8,9]])
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
n[2][1]

8

In [28]:
n[0,1]=654

In [30]:
n

array([[  1, 654,   3],
       [  4,   5,   6],
       [  7,   8,   9]])

In [31]:
n[1]

array([4, 5, 6])

In [35]:
n[:,1] ##get all the rows for column index 1

array([654,   5,   8])

In [37]:
n[:,2]=[15,36,45]
n

array([[  1, 654,  15],
       [  4,   5,  36],
       [  7,   8,  45]])

# **Randomly Generate arrays**

In [66]:
# np.random.seed(2)
100*np.random.rand(5,2)

array([[54.42081601,  8.20949223],
       [36.63424017, 85.0850504 ],
       [40.6275043 ,  2.72023659],
       [24.7177239 ,  6.71443707],
       [99.38520114, 97.05803134]])

In [63]:
np.random.randn(5,2)

array([[ 9.76147160e-06,  5.42352572e-01],
       [-3.13508197e-01,  7.71011738e-01],
       [-1.86809065e+00,  1.73118467e+00],
       [ 1.46767801e+00, -3.35677339e-01],
       [ 6.11340780e-01,  4.79705919e-02]])

# **Element-wise operations**

In [65]:
a=np.arange(5)
a

array([0, 1, 2, 3, 4])

In [69]:
b=((a*2+10)**2)/10
b

array([10. , 14.4, 19.6, 25.6, 32.4])

In [74]:
a/b

array([0.        , 0.06944444, 0.10204082, 0.1171875 , 0.12345679])

# **Comparison operations**

In [75]:
a

array([0, 1, 2, 3, 4])

In [76]:
a>=2

array([False, False,  True,  True,  True])

In [77]:
a[a>=2]

array([2, 3, 4])

In [78]:
b

array([10. , 14.4, 19.6, 25.6, 32.4])

In [85]:
a>b

array([False, False, False, False, False])

In [82]:
b>a

array([ True,  True,  True,  True,  True])

# **Summarizing operations**

In [86]:
a.min()

0

In [87]:
a.max()

4

In [88]:
a.sum()

10

In [90]:
a.mean()

2.0

In [91]:
a.std()

1.4142135623730951

In [93]:
n

array([[  1, 654,  15],
       [  4,   5,  36],
       [  7,   8,  45]])

In [95]:
n.sum()

775

In [96]:
n.min()

1

In [97]:
n.max()

654