# **Importing Numpy**

In [1]:
import numpy as np

# **Vector Operations**

In [2]:
u=np.array([2,4,5,6])

In [3]:
u

array([2, 4, 5, 6])

In [4]:
v=np.array([1,0,0,2])

In [5]:
v

array([1, 0, 0, 2])

In [6]:
u+v

array([3, 4, 5, 8])

In [7]:
u-v

array([1, 4, 5, 4])

In [8]:
2*u

array([ 4,  8, 10, 12])

# **Multiplication**

## **Vector-Vector Multiplication**

In [13]:
def vector_vector_multiplication(u,v):
    assert u.shape[0]==v.shape[0]
    n=u.shape[0]
    result=0.0
    for i in range(n):
        result+=u[i]*v[i]
    return result

In [14]:
vector_vector_multiplication(u,v)

14.0

In [16]:
# Numpy builtin funciton for vector-vector multipliaction
u.dot(v)

14

## **Matrix-Vector Multiplication**

In [18]:
U=np.array([[2,4,5,6],
           [1,2,1,2],
           [3,1,2,1]])

In [19]:
U

array([[2, 4, 5, 6],
       [1, 2, 1, 2],
       [3, 1, 2, 1]])

In [24]:
v

array([1, 0, 0, 2])

In [20]:
U.shape

(3, 4)

In [27]:
def matrix_vector_multiplication(U,v):
    assert U.shape[1]==v.shape[0]
    num_rows=U.shape[0]
    result=np.zeros(num_rows)
    for i in range(num_rows):
        result[i]=vector_vector_multiplication(U[i],v)
        # result[i]=U[i].dot(v)
    return result

In [28]:
matrix_vector_multiplication(U,v)

array([14.,  5.,  5.])

In [29]:
U.dot(v)

array([14,  5,  5])

## **Matrix-Matrix Multiplication**

In [31]:
U, U.shape

(array([[2, 4, 5, 6],
        [1, 2, 1, 2],
        [3, 1, 2, 1]]),
 (3, 4))

In [32]:
V=np.array([[1,1,2],
            [0,0.5,1],
            [0,2,1],
            [2,1,0]])

In [33]:
V,V.shape

(array([[1. , 1. , 2. ],
        [0. , 0.5, 1. ],
        [0. , 2. , 1. ],
        [2. , 1. , 0. ]]),
 (4, 3))

In [34]:
def matrix_matrix_multiplication(U,V):
    assert U.shape[1]==V.shape[0]
    num_rows=U.shape[0]
    num_cols=V.shape[1]
    result=np.zeros((num_rows,num_cols))

    for col in range(num_cols):
        vi=V[:,col]
        Uvi=matrix_vector_multiplication(U,vi)
        result[:,col]=Uvi
    return result

In [35]:
matrix_matrix_multiplication(U,V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [36]:
U.dot(V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

# **Identity Matrix**

In [49]:
I3=np.eye(3)

In [47]:
U

array([[2, 4, 5, 6],
       [1, 2, 1, 2],
       [3, 1, 2, 1]])

In [50]:
I3.dot(U)

array([[2., 4., 5., 6.],
       [1., 2., 1., 2.],
       [3., 1., 2., 1.]])

In [51]:
I4=np.eye(4)

In [52]:
U.dot(I4)

array([[2., 4., 5., 6.],
       [1., 2., 1., 2.],
       [3., 1., 2., 1.]])

# **Inverse of a matrix**

In [59]:
Vs=V[[0,1,2,]]

In [60]:
Vs

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [64]:
Vs_inv=np.linalg.inv(Vs)
Vs_inv

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])

In [65]:
Vs.dot(Vs_inv)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])