# **Homework for Module 1**

## **Question 1**
What's the version of Pandas that you installed?
You can get the version information using the __version__ field:

In [1]:
import numpy as np
import pandas as pd

In [2]:
pd.__version__

'2.2.2'

## **Getting the Data**
For all the questions below we are using the laptops dataset provided in the homework.
- __[Laptops](https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv)__

## **Question 2: Records count**
How many records are in the dataset?
- 12
- 1000
- 2160
- 12160

In [78]:
# Reading the dataset
df=pd.read_csv("laptops.csv")

In [79]:
df.head()

Laptop Status   Brand  \
0  ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...    New    Asus   
1  Alurin Go Start Intel Celeron N4020/8GB/256GB ...    New  Alurin   
2  ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...    New    Asus   
3  MSI Katana GF66 12UC-082XES Intel Core i7-1270...    New     MSI   
4  HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...    New      HP   

        Model            CPU  RAM  Storage Storage type       GPU  Screen  \
0  ExpertBook  Intel Core i5    8      512          SSD       NaN    15.6   
1          Go  Intel Celeron    8      256          SSD       NaN    15.6   
2  ExpertBook  Intel Core i3    8      256          SSD       NaN    15.6   
3      Katana  Intel Core i7   16     1000          SSD  RTX 3050    15.6   
4         15S  Intel Core i5   16      512          SSD       NaN    15.6   

  Touch  Final Price  
0    No      1009.00  
1    No       299.00  
2    No       789.00  
3    No      1199.00  
4    No       669.01

In [80]:
df.shape

(2160, 12)

In [81]:
print(f"The dataset has {df.shape[0]} records.")

The dataset has 2160 records.


## **Question 3: Laptop brands**
How many laptop brands are presented in the dataset?
- 12
- 27
- 28
- 2160

In [82]:
df.nunique()

Laptop          2160
Status             2
Brand             27
Model            121
CPU               28
RAM                9
Storage           12
Storage type       2
GPU               44
Screen            29
Touch              2
Final Price     1440
dtype: int64

In [83]:
print(f"The dataset has {df['Brand'].nunique()} unique laptop brands.")

The dataset has 27 unique laptop brands.


## **Question 4: Missing values**
How many columns in the dataset have missing values?
- 0
- 1
- 2
- 3

In [84]:
df.isnull().sum()

Laptop             0
Status             0
Brand              0
Model              0
CPU                0
RAM                0
Storage            0
Storage type      42
GPU             1371
Screen             4
Touch              0
Final Price        0
dtype: int64

3 columns in the dataset have missing values.

## **Question 5: Maximum final price**
What's the maximum final price of Dell notebooks in the dataset?
- 869
- 3691
- 3849
- 3936

In [85]:
print(f"The maximum final price of Dell notebooks in the dataset is {df[df["Brand"]=="Dell"]["Final Price"].max():.0f}.")

The maximum final price of Dell notebooks in the dataset is 3936.


## **Question 6: Median value of Screen**
1. Find the median value of `Screen` column in the dataset.
2. Next, calculate the most frequent value of the same `Screen` column.
3. Use `fillna` method to fill the missing values in `Screen` column with the most frequent value from the previous step.
4. Now, calculate the median value of `Screen` once again.

Has it changed?

> Hint: refer to existing `mode` and `median` functions to complete the task.

- Yes
- No

In [86]:
# Answer 1: 
print(f"The median value of Screen column in the dataset is {df["Screen"].median()}")

The median value of Screen column in the dataset is 15.6


In [87]:
# Answer 2: Method 1
df.groupby("Screen").Screen.agg("count")

Screen
10.10       1
10.50       7
10.95       1
11.60      16
12.00       4
12.30      13
12.40       6
12.50       1
13.00      27
13.30     131
13.40      19
13.50      19
13.60      11
13.90       2
14.00     392
14.10      11
14.20      14
14.40       6
14.50       3
15.00      21
15.30       8
15.40       5
15.60    1009
16.00     174
16.10      48
16.20      10
17.00      33
17.30     161
18.00       3
Name: Screen, dtype: int64

In [88]:
# Answer 2: Method 2
df["Screen"].mode()

0    15.6
Name: Screen, dtype: float64

In [89]:
print(f"The most frequent value for the 'Screen' column is {df["Screen"].mode()[0]}")

The most frequent value for the 'Screen' column is 15.6


In [91]:
# Answer 3
df[df["Screen"].isna()]

Laptop Status   Brand  \
624   Acer Extensa 15 EX215-54 Intel Core i5-1135G7/...    New    Acer   
1430  HP ENVY x360 2-in-1 Laptop 15-ew0008np Intel C...    New      HP   
1503  Lenovo IdeaPad Gaming 3 15ACH6 AMD Ryzen 5 560...    New  Lenovo   
1548  Lenovo ThinkPad P15 Gen 2 Intel Core i7-11850H...    New  Lenovo   

         Model            CPU  RAM  Storage Storage type        GPU  Screen  \
624    Extensa  Intel Core i5    8      256          SSD        NaN     NaN   
1430      Envy  Intel Core i7   16      512          SSD   RTX 2050     NaN   
1503   IdeaPad    AMD Ryzen 5   16      512          SSD   RTX 3060     NaN   
1548  ThinkPad  Intel Core i7   16      512          SSD  RTX A2000     NaN   

     Touch  Final Price  
624     No       524.99  
1430   Yes      1863.52  
1503    No      1505.00  
1548    No      2569.00

In [92]:
df["Screen"]=df['Screen'].fillna(df["Screen"].mode()[0])

In [93]:
df[df["Screen"].isna()]

Empty DataFrame
Columns: [Laptop, Status, Brand, Model, CPU, RAM, Storage, Storage type, GPU, Screen, Touch, Final Price]
Index: []

In [94]:
# Answer 4
print(f"The median value of Screen column after filling 'NaN' with mode value in the dataset is {df["Screen"].median()}")

The median value of Screen column after filling 'NaN' with mode value in the dataset is 15.6


No, The median of the 'Screen' column did not change after filling the 'NaN' values in the 'Screen' column with the most frequent value (mode).

## **Question 7: Sum of weights**
1. Select all the "Innjoo" laptops from the dataset.
2. Select only columns `RAM`, `Storage`, `Screen`.
3. Get the underlying NumPy array. Let's call it `X`.
4. Compute matrix-matrix multiplication between the transpose of `X` and `X`. To get the transpose, use `X.T`. Let's call the result `XTX`.
5. Compute the inverse of `XTX`.
6. Create an array `y` with values `[1100, 1300, 800, 900, 1000, 1100]`.
7. Multiply the inverse of `XTX` with the transpose of `X`, and then multiply the result by `y`. Call the result `w`.
8. What's the sum of all the elements of the result?

> **Note**: You just implemented linear regression. We'll talk about it in the next lesson.

- 0.43
- 45.29
- 45.58
- 91.30

In [100]:
df[df['Brand']=="Innjoo"]

Laptop Status   Brand Model  \
1478  InnJoo Voom Excellence Intel Celeron N4020/8GB...    New  Innjoo  Voom   
1479  InnJoo Voom Excellence Pro Intel Celeron N4020...    New  Innjoo  Voom   
1480  Innjoo Voom Intel Celeron N3350/4GB/64GB eMMC/...    New  Innjoo  Voom   
1481  Innjoo Voom Laptop Max Intel Celeron N3350/6GB...    New  Innjoo  Voom   
1482  Innjoo Voom Laptop Pro Intel Celeron N3350/6GB...    New  Innjoo  Voom   
1483  Innjoo Voom Pro Intel Celeron N3350/6GB/128GB ...    New  Innjoo  Voom   

                CPU  RAM  Storage Storage type  GPU  Screen Touch  Final Price  
1478  Intel Celeron    8      256          SSD  NaN    15.6    No       311.37  
1479  Intel Celeron    8      512          SSD  NaN    15.6    No       392.55  
1480  Intel Celeron    4       64         eMMC  NaN    14.1    No       251.40  
1481  Intel Celeron    6       64         eMMC  NaN    14.1    No       383.61  
1482  Intel Celeron    6      128          SSD  NaN    14.1    No       317.02  
1483  Intel Celeron    6      128         eMMC  NaN    14.1    No       431.38

In [98]:
df_new = df[df['Brand']=="Innjoo"]

In [102]:
df_new[["RAM","Storage","Screen"]]

RAM  Storage  Screen
1478    8      256    15.6
1479    8      512    15.6
1480    4       64    14.1
1481    6       64    14.1
1482    6      128    14.1
1483    6      128    14.1

In [139]:
 X=df_new[["RAM","Storage","Screen"]].to_numpy()
X

array([[  8. , 256. ,  15.6],
       [  8. , 512. ,  15.6],
       [  4. ,  64. ,  14.1],
       [  6. ,  64. ,  14.1],
       [  6. , 128. ,  14.1],
       [  6. , 128. ,  14.1]])

In [147]:
XTX=X.T@X
XTX

array([[2.52000e+02, 8.32000e+03, 5.59800e+02],
       [8.32000e+03, 3.68640e+05, 1.73952e+04],
       [5.59800e+02, 1.73952e+04, 1.28196e+03]])

In [142]:
XTX_inv=np.linalg.inv(XTX)
XTX_inv

array([[ 2.78025381e-01, -1.51791334e-03, -1.00809855e-01],
       [-1.51791334e-03,  1.58286725e-05,  4.48052175e-04],
       [-1.00809855e-01,  4.48052175e-04,  3.87214888e-02]])

In [143]:
y=np.array([1100, 1300, 800, 900, 1000, 1100])
y

array([1100, 1300,  800,  900, 1000, 1100])

In [144]:
XTX_inv.shape, X.T.shape, y.shape

((3, 3), (3, 6), (6,))

In [145]:
w= (XTX_inv.dot(X.T)).dot(y)
w

array([45.58076606,  0.42783519, 45.29127938])

In [146]:
w.sum()

91.29988062995815

**Difference between numpy .dot() and @** <br>
__[Reference Medium article](https://medium.com/@debopamdeycse19/dot-vs-matmul-in-numpy-which-one-is-best-suited-for-your-needs-dbd27c56ca33)__ <br>
__[Reference stackoverflow article](https://stackoverflow.com/questions/34142485/difference-between-numpy-dot-and-python-3-5-matrix-multiplication)__